name: Scan failed branch test
on:
  push: 
    branches:
    - 'v[0-9]+.[0-9]+'

jobs:
  scan:
    name: Scan
    runs-on: ubuntu-20.04
    steps:
      - name: Check Commit Message
        run: |
          if [[ "${{ github.event.head_commit.message }}" == "#NORUN"* ]]; then
            echo "Commit message starts with #NORUN. Skipping this workflow."
            exit 78  # Exit with a neutral status code to prevent the workflow from running.
          fi


      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@master
        with:
            scan-type: 'fs'
            ignore-unfixed: true
            format: 'table'
            output: 'trivy-results.txt'
            severity: 'CRITICAL,HIGH'  # if want to fail, add 'HIGH' in it

    #   - name: Debug Workspace Contents
    #     run: cat trivy-results.txt

      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          # Slack channel id, channel name, or user id to post message.
          # See also: https://api.slack.com/methods/chat.postMessage#channels
          channel-id: ${{secrets.SLACK_CHANNEL_ID}}
          # For posting a rich message using Block Kit
          payload: |
            {
              "text": "TESTTEST",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "New request"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Type:*\nPaid Time Off"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Created by:*\n<example.com|Fred Enriquez>"
                    }
                  ]
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*When:*\nAug 10 - Aug 13"
                    }
                  ]
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "<https://example.com|View request>"
                  }
                }
              ]              
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
    
      - name: Upload file to Slack
        uses: MeilCli/slack-upload-file@v3
        with:
          slack_token: ${{ secrets.BOT_TOKEN }} # act --secret-file tmp.github_secrets
          channel_id: ${{ secrets.SLACK_CHANNEL_ID }}
          file_path: 'trivy-results.txt'
          initial_comment: 'Scan report by 11'
          file_type: 'text'
          file_name: 'trivy-results.txt'
          title: 'Trivy-Result'
        #   thread_ts: 'option'
